#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

RPC_URL="${MONAD_RPC_URL:-https://rpc.monad.xyz}"
CHAIN_ID="${MONAD_CHAIN_ID:-143}"

if [ -f .env ]; then
  set -a
  # shellcheck disable=SC1091
  source .env
  set +a
fi

if [ -z "${DEPLOYER_PRIVATE_KEY:-}" ] && [ -n "${PRIVATE_KEY:-}" ]; then
  export DEPLOYER_PRIVATE_KEY="$PRIVATE_KEY"
fi

if [ -z "${DEPLOYER_PRIVATE_KEY:-}" ]; then
  echo "Missing DEPLOYER_PRIVATE_KEY or PRIVATE_KEY in .env"
  echo ""
  echo "Add to .env (one line only, no quotes):"
  echo "  DEPLOYER_PRIVATE_KEY=0x..."
  echo ""
  echo "Tip: a duplicate empty DEPLOYER_PRIVATE_KEY= line will overwrite a valid key."
  exit 1
fi

echo "Deploying BacktestRegistry to Monad mainnet (chain $CHAIN_ID)..."
OUT=$(forge script script/Deploy.s.sol:Deploy \
  --rpc-url "$RPC_URL" \
  --broadcast \
  --chain-id "$CHAIN_ID" \
  -vv 2>&1)

echo "$OUT"

ADDRESS=$(echo "$OUT" | grep -Eo '0x[a-fA-F0-9]{40}' | tail -1)

if [ -z "$ADDRESS" ]; then
  echo "Could not parse deployed address from forge output"
  exit 1
fi

cat > src/lib/deployed.ts <<EOF
// Auto-generated by scripts/deploy-mainnet.sh — do not edit manually
export const BACKTEST_REGISTRY_ADDRESS =
  "${ADDRESS}" as const;

export const MONAD_CHAIN_ID = ${CHAIN_ID} as const;
EOF

echo ""
echo "Deployed: $ADDRESS"
echo "Written to src/lib/deployed.ts"
echo "Explorer: https://monadvision.com/address/$ADDRESS"
